### ISSUE TITLE
How to register projection with ctor dependency?

### ISSUE THREAD

**Issue by koenmetsu** [Informatievlaanderen/projector#10]
https://github.com/Informatievlaanderen/projector/blob/master/src/Be.Vlaanderen.Basisregisters.Projector/ContainerBuilderExtensions.cs#L15 => requires an empty ctor.

I'd use the code it references, https://github.com/Informatievlaanderen/projector/blob/master/src/Be.Vlaanderen.Basisregisters.Projector/ContainerBuilderExtensions.cs#L30, but `IConnectedProjection` seems te be internal.

**Comment by koenmetsu** [comment]
Manually `new`-ing is not an option, btw. I want the container to handle creation of deps.

**Comment by CumpsD** [comment]
@ridingwolf

**Comment by ridingwolf** [comment]
Was not possible, added overload with access to the container in https://github.com/Informatievlaanderen/projector/pull/11

```csharp
builder
    .RegisterProjections<Projections, ProjectionContext>(
        container => new Projections(container.Resolve<TDependency>(), ...)
    );
builder
    .RegisterProjections<Projections, ProjectionContext>(
        container => container.Resolve<Projections>()
    );
```
